/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false` (hash: f2136769f34046425b0d757ca2c78bf8)
interface __BaseEnv_Env {
	LOADER: WorkerLoader;
	PUBLIC_ORIGIN: string;
	ACCESS_TEAM_DOMAIN: string;
	ACCESS_AUD: string;
	CONNECTION_JSON: string;
	SOURCE: DurableObjectNamespace<import("./src/index").ApiSource>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "ApiSource";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "PUBLIC_ORIGIN" | "ACCESS_TEAM_DOMAIN" | "ACCESS_AUD" | "CONNECTION_JSON">> {}
}
