import { customerPageEnd, customerPageStart } from './customer-page-shell';
import { customerLoadingIndicator } from './customer-page-theme';
/** The bootstrap page contains no configuration, provider identifiers, or credentials in its HTML. */
export function customerSetupPage(): Response {
  const nonce = crypto.randomUUID().replaceAll('-', '');
  return new Response(String.raw`${customerPageStart('Set up your Ankka Gateway', 'form')}<p class="eyebrow">In your Cloudflare account</p><h1 id="heading" tabindex="-1">Set up your gateway</h1><p id="intro">Choose your gateway’s addresses and who will administer it.</p><div id="progress">${customerLoadingIndicator}</div><p id="message" role="status" aria-live="polite">Checking your secure setup session…</p>
<section id="no-domains" class="domain-guide" hidden aria-labelledby="domain-guide-heading">
<h2 id="domain-guide-heading">Give your team a place to connect</h2><p>Ankka uses a custom domain for your management page and the MCP address your team connects to. For example:</p>
<dl class="address-examples"><div><dt>Management page</dt><dd>manage.example.com</dd></div><div><dt>MCP address</dt><dd>mcp.example.com</dd></div></dl>
<ol class="domain-steps"><li><strong>Open your Cloudflare account</strong><p>Select the same account you approved for this setup.</p></li><li><strong>Add a domain you own</strong><p>Follow Cloudflare’s instructions to connect the domain and update its DNS settings.</p></li><li><strong>Wait until the domain is Active</strong><p>Then return to the installer and choose <strong>Start a new deployment</strong>. Your next approval checks the account’s domains again.</p></li></ol>
<div class="actions"><a class="button-link" href="https://dash.cloudflare.com/" target="_blank" rel="noopener noreferrer">Open Cloudflare ↗</a><a href="https://developers.cloudflare.com/fundamentals/manage-domains/add-site/" target="_blank" rel="noopener noreferrer">How to add a domain ↗</a></div>
<a href="https://deploy.ankka.ai">Return to the installer</a><p class="domain-note">Domain activation can take time. This page does not refresh the domain list; start a new deployment once Cloudflare shows the domain as Active.</p>
</section>
<form id="setup" hidden>
<div class="grid"><label>Gateway name<input id="name" autocomplete="organization" maxlength="80" required placeholder="Your team’s gateway"><small>Shown on your management page and in Cloudflare.</small></label>
<label>Domain<select id="domain" required></select><small>Active domains available in the Cloudflare account you selected.</small></label></div>
<div class="grid"><label>Management address<input id="management" inputmode="url" autocomplete="off" required></label><label>MCP address<input id="portal" inputmode="url" autocomplete="off" required></label></div>
<label>Administrator email<input id="email" type="email" autocomplete="email" required></label>
<label><span>Additional administrators <small>Optional</small></span><textarea id="admins" rows="2" placeholder="One email per line"></textarea></label>
<button id="review-button" type="submit">Review setup</button>
</form>
<section id="review" hidden aria-label="Review your gateway"><h2>Review your gateway</h2><dl id="summary"></dl><details><summary>Resources to create or configure</summary><ul id="resources"></ul></details><p>Cloudflare will check these addresses again before making changes. Your team’s MCP sources are connected after setup.</p><div class="actions"><button id="approve" type="button">Approve and finish setup</button><button id="edit" type="button" class="secondary">Edit</button></div><small>This second Cloudflare approval is temporary. No Cloudflare token is saved.</small></section>
<p id="restart" hidden><a href="https://deploy.ankka.ai">Return to the installer</a> to review your deployment. An unfinished gateway may still exist in your Cloudflare account.</p>
<script nonce="${nonce}">
(()=>{
const $=id=>document.getElementById(id), root='/__ankka/install';let busy=false,previousDomain='',setup=null;
const message=(value)=>{$('message').textContent=value};
const errors={active_zone_required:'Add an active domain to your Cloudflare account, then return to the installer to start a new deployment.',gateway_name_invalid:'Enter a gateway name with at least two letters or numbers.',admin_email_invalid:'Enter a valid administrator email.',additional_admin_emails_invalid:'Check the additional administrator emails.',management_hostname_invalid:'Enter a management hostname under the selected domain.',portal_hostname_invalid:'Enter a different MCP hostname under the selected domain.',gateway_hostnames_invalid:'Choose two different hostnames under the selected domain.',selection_contract_invalid:'Check your gateway details before continuing.'};
async function api(path,body){const response=await fetch(root+path,{method:body===undefined?'GET':'POST',headers:body===undefined?{}:{'content-type':'application/json'},body:body===undefined?undefined:JSON.stringify(body),credentials:'same-origin',cache:'no-store'});const value=await response.json();if(!response.ok){if(response.status===403||response.status===410){$('restart').hidden=false;throw new Error('Your setup session has expired. Return to the installer to review your deployment before starting again.')}if(value.error==='setup_locked')throw new Error('Your final approval has already started. Finish it in Cloudflare.');throw new Error(errors[value.reason]||'Setup could not continue. Check your entries and try again.')}return value}
async function action(run){if(busy)return;busy=true;$('progress').hidden=!($('setup').hidden&&$('review').hidden&&$('no-domains').hidden);document.querySelectorAll('button').forEach(b=>b.disabled=true);try{await run()}catch(error){message(error.message||'Setup could not continue. Please try again.')}finally{busy=false;$('progress').hidden=true;document.querySelectorAll('button').forEach(b=>b.disabled=false)}}
function defaults(){const domain=$('domain').value;for(const [id,prefix] of [['management','manage'],['portal','mcp']]){if(!$(id).value||$(id).value===prefix+'.'+previousDomain)$(id).value=prefix+'.'+domain}previousDomain=domain}
function fill(value){setup=value;const empty=value.availableZones.length===0;$('no-domains').hidden=!empty;$('setup').hidden=empty;if(empty){$('heading').textContent='Add a custom domain';$('intro').textContent='Your setup is ready in Cloudflare. A domain is the next step.';message('No active domains were found in the account you approved.');return}$('heading').textContent='Set up your gateway';$('intro').textContent='Choose your gateway’s addresses and who will administer it.';$('domain').replaceChildren(...value.availableZones.map(zone=>{const option=document.createElement('option');option.value=zone.name;option.textContent=zone.name;return option}));if(value.selection){const b=value.selection.basics;$('name').value=b.gatewayName;$('domain').value=b.zoneName;$('management').value=b.managementHostname;$('portal').value=b.portalHostname;$('email').value=b.adminEmail;$('admins').value=b.additionalAdminEmails.join('\n')}defaults();message('Choose your gateway details. You will review them before the final approval.')}
function review(value){setup=value;const plan=value.plan,b=value.selection.basics;$('summary').replaceChildren();for(const [label,text] of [['Gateway',b.gatewayName],['Management address',b.managementHostname],['MCP address',b.portalHostname],['Administrators',plan.managementAdminEmails.join(', ')]]){const dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=label;dd.textContent=text;$('summary').append(dt,dd)}$('resources').replaceChildren(...[...plan.managementResources,...plan.gatewayResources].map(resource=>{const li=document.createElement('li');li.textContent=resource.name;return li}));$('setup').hidden=true;$('review').hidden=false;$('edit').hidden=value.approvalExpired===true;$('approve').textContent=value.approvalExpired===true?'Start a fresh approval':'Approve and finish setup';message(value.approvalExpired===true?'Your Cloudflare approval expired before setup started. Start a fresh approval for these same gateway details.':'Review these details, then approve the final installation in Cloudflare.');$('heading').focus()}
$('domain').addEventListener('change',defaults);
$('setup').addEventListener('submit',event=>{event.preventDefault();void action(async()=>{message('Preparing your deployment plan…');const selection={schemaVersion:1,basics:{gatewayName:$('name').value,zoneName:$('domain').value,managementHostname:$('management').value,portalHostname:$('portal').value,adminEmail:$('email').value,additionalAdminEmails:$('admins').value.split(/[\n,]+/).map(s=>s.trim()).filter(Boolean)},firstSource:null};review(await api('/configuration',selection))})});
$('edit').addEventListener('click',()=>{$('review').hidden=true;fill(setup)});
$('approve').addEventListener('click',()=>{void action(async()=>{message('Opening Cloudflare for your final approval…');const value=await api('/oauth/start',{});const url=new URL(value.authorizationUrl);if(url.origin!=='https://dash.cloudflare.com')throw new Error('The authorization link could not be verified.');location.assign(url.href)})});
void action(async()=>{const raw=location.hash.slice(1);history.replaceState(null,'',root);if(raw){const normalized=raw.replace(/-/g,'+').replace(/_/g,'/');const handoff=JSON.parse(new TextDecoder().decode(Uint8Array.from(atob(normalized.padEnd(Math.ceil(normalized.length/4)*4,'=')),c=>c.charCodeAt(0))));await api('/continue',handoff);if(!handoff.setupPermit){const value=await api('/oauth/start',{});location.assign(value.authorizationUrl);return}}const value=await api('/setup');fill(value);if(value.plan)review(value)}).then(()=>{if($('setup').hidden&&$('review').hidden&&$('no-domains').hidden)$('restart').hidden=false});
})();
</script>${customerPageEnd}`, { headers: {
    'content-type': 'text/html; charset=utf-8', 'cache-control': 'no-store',
    'content-security-policy': `default-src 'none'; script-src 'nonce-${nonce}'; connect-src 'self'; style-src 'unsafe-inline'; frame-ancestors 'none'; base-uri 'none'; form-action 'none'`,
    'referrer-policy': 'no-referrer', 'x-content-type-options': 'nosniff', 'cross-origin-opener-policy': 'same-origin',
  } });
}
