/**
 * The bootstrap page contains no configuration, provider identifiers, or credentials in its HTML.
 *
 * Its management token step takes one pasted value in a field that is not
 * echoed, has no `name` (so no form submission could ever carry it) and is
 * emptied as soon as it is read. The value goes once, in the body of a
 * same-origin POST under the setup session, to this same Worker, and is never
 * placed in a URL, a fragment, storage, or the page again.
 */
export function customerSetupPage(): Response {
  const nonce = crypto.randomUUID().replaceAll('-', '');
  return new Response(String.raw`<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="referrer" content="no-referrer"><title>Set up your Ankka Gateway</title>
<style>
:root{color-scheme:dark;font:16px/1.5 system-ui,sans-serif;background:#14130f;color:#eeeae0}*{box-sizing:border-box}body{margin:0}main{max-width:44rem;margin:5rem auto;padding:0 1.5rem}h1{font-size:2rem;letter-spacing:-.035em;line-height:1.15}h2{font-size:1.1rem}p,small{color:#b9b5aa}.eyebrow{font-size:.75rem;letter-spacing:.12em;text-transform:uppercase;color:#d8ef91}label{display:grid;gap:.4rem;margin:1.1rem 0;font-weight:550}input,select,textarea{font:inherit;color:inherit;background:#201f19;border:1px solid #555146;border-radius:6px;padding:.75rem;width:100%}small{font-size:.8rem;font-weight:400}button{font:inherit;cursor:pointer;border:1px solid #d8ef91;border-radius:6px;background:#d8ef91;color:#14130f;padding:.75rem 1.1rem;font-weight:600}button.secondary{background:transparent;color:#eeeae0;border-color:#555146}button:disabled{opacity:.6;cursor:wait}input:focus-visible,select:focus-visible,textarea:focus-visible,button:focus-visible{outline:2px solid #d8ef91;outline-offset:3px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:1rem}.actions{display:flex;gap:.75rem;margin:1.5rem 0}dl{margin:1.5rem 0}dt{color:#b9b5aa;font-size:.8rem}dd{margin:0 0 1rem;overflow-wrap:anywhere}li{margin:.4rem 0}#message{min-height:1.5em}a{color:#d8ef91}[hidden]{display:none!important}@media(max-width:600px){main{margin:2rem auto}.grid{grid-template-columns:1fr;gap:0}}
.domain-guide{margin:1.5rem 0;padding:1.5rem;border:1px solid #454237;border-radius:12px;background:#1b1a15}.domain-guide h2{margin-top:0}.address-examples{display:grid;grid-template-columns:1fr 1fr;gap:1px;background:#454237;border:1px solid #454237;border-radius:8px;overflow:hidden;margin:1.25rem 0}.address-examples div{padding:1rem;background:#14130f}.address-examples dt{margin-bottom:.35rem}.address-examples dd{margin:0;font-family:ui-monospace,monospace;font-size:.9rem}.domain-steps{padding-left:1.4rem;margin:1.5rem 0}.domain-steps li{padding-left:.35rem;margin:1.1rem 0}.domain-steps li::marker{color:#d8ef91}.domain-steps p{margin:.25rem 0;font-size:.9rem}.actions{flex-wrap:wrap;align-items:center}.button-link{display:inline-flex;align-items:center;justify-content:center;min-height:44px;padding:.65rem 1rem;border:1px solid #d8ef91;border-radius:6px;background:#d8ef91;color:#14130f;font-weight:600;text-decoration:none}.button-link:active{transform:scale(.98)}a:focus-visible{outline:2px solid #d8ef91;outline-offset:4px}.domain-note{font-size:.85rem;margin-bottom:0}code{font:.9em ui-monospace,monospace;overflow-wrap:anywhere}#credential-note{color:#eeeae0}@media(max-width:600px){.domain-guide{padding:1.15rem}.address-examples{grid-template-columns:1fr}.domain-guide .actions{align-items:stretch;flex-direction:column}}
</style></head><body><main><p class="eyebrow">Ankka · In your Cloudflare account</p><h1 id="heading" tabindex="-1">Set up your gateway</h1><p id="intro">Choose your gateway’s addresses and who will administer it.</p><p id="message" role="status" aria-live="polite">Checking your secure setup session…</p>
<section id="no-domains" class="domain-guide" hidden aria-labelledby="domain-guide-heading">
<h2 id="domain-guide-heading">Give your team a place to connect</h2><p>Ankka uses a custom domain for your management page and the MCP address your team connects to. For example:</p>
<dl class="address-examples"><div><dt>Management page</dt><dd>manage.example.com</dd></div><div><dt>MCP address</dt><dd>mcp.example.com</dd></div></dl>
<ol class="domain-steps"><li><strong>Open your Cloudflare account</strong><p>Select the same account you approved for this setup.</p></li><li><strong>Add a domain you own</strong><p>Follow Cloudflare’s instructions to connect the domain and update its DNS settings.</p></li><li><strong>Wait until the domain is Active</strong><p>Then return to the installer and choose <strong>Start a new deployment</strong>. Your next approval checks the account’s domains again.</p></li></ol>
<div class="actions"><a class="button-link" href="https://dash.cloudflare.com/" target="_blank" rel="noopener noreferrer">Open Cloudflare ↗</a><a href="https://developers.cloudflare.com/fundamentals/manage-domains/add-site/" target="_blank" rel="noopener noreferrer">How to add a domain ↗</a></div>
<a href="https://deploy.ankka.ai">Return to the installer</a><p class="domain-note">Domain activation can take time. This page does not refresh the domain list; start a new deployment once Cloudflare shows the domain as Active.</p>
</section>
<form id="setup" hidden>
<label>Gateway name<input id="name" autocomplete="organization" maxlength="80" required placeholder="Your team’s gateway"><small>Shown on your management page and in Cloudflare.</small></label>
<label>Domain<select id="domain" required></select><small>Active domains available in the Cloudflare account you selected.</small></label>
<div class="grid"><label>Management address<input id="management" inputmode="url" autocomplete="off" required></label><label>MCP address<input id="portal" inputmode="url" autocomplete="off" required></label></div>
<label>Administrator email<input id="email" type="email" autocomplete="email" required></label>
<label>Additional administrators <small>Optional</small><textarea id="admins" rows="2" placeholder="One email per line"></textarea></label>
<button id="review-button" type="submit">Review setup</button>
</form>
<section id="review" hidden aria-label="Review your gateway"><h2>Review your gateway</h2><dl id="summary"></dl><details><summary>Resources to create or configure</summary><ul id="resources"></ul></details><p>Cloudflare will check these addresses again before making changes. Your team’s MCP sources are connected after setup.</p>
<section id="credential" class="domain-guide" hidden aria-labelledby="credential-heading">
<h2 id="credential-heading">Management token</h2>
<p>Adding a source or giving a teammate access writes to your Cloudflare account, and the approvals in this setup are temporary. Your gateway needs one credential of its own for that work: an account API token with two permissions, <strong>Access: Apps and Policies Edit</strong> and <strong>MCP Portals Edit</strong>.</p>
<p>Creating it needs a Super Administrator or Administrator of your Cloudflare account. Cloudflare cannot limit this token to your gateway: it can edit every Access policy in the account. This page sends it only to your own gateway, which keeps it in memory and saves it as the encrypted secret <code>ANKKA_MANAGEMENT_TOKEN</code> when setup finishes. It never passes through anything Ankka hosts.</p>
<div id="credential-entry">
<ol class="domain-steps"><li><a id="credential-link" class="button-link" href="https://dash.cloudflare.com/" target="_blank" rel="noopener noreferrer">Create the token in Cloudflare ↗</a><p>The link fills in both permissions and the name <strong id="credential-name"></strong>, so you can find the token again later. Choose your account, create the token, and copy it.</p></li>
<li><form id="credential-form"><label for="credential-value">Paste the token<input id="credential-value" type="password" autocomplete="off" autocapitalize="off" spellcheck="false" maxlength="96" required></label><div class="actions"><button id="credential-save" type="submit">Use this token</button><button id="credential-skip" type="button" class="secondary">Continue without a token</button></div></form></li></ol>
<p class="domain-note">Without the token, adding sources and managing team access stay disabled. You can add it later in Settings.</p>
</div>
<p id="credential-note" role="status" aria-live="polite" hidden></p><button id="credential-change" type="button" class="secondary" hidden>Use a different token</button>
</section>
<div class="actions"><button id="approve" type="button">Approve and finish setup</button><button id="edit" type="button" class="secondary">Edit</button></div><small>This second Cloudflare approval is temporary. Your gateway revokes and discards it when setup finishes.</small></section>
<p id="restart" hidden><a href="https://deploy.ankka.ai">Return to the installer</a> to review your deployment. An unfinished gateway may still exist in your Cloudflare account.</p>
<script nonce="${nonce}">
(()=>{
const $=id=>document.getElementById(id), root='/__ankka/install';let busy=false,previousDomain='',setup=null;
const message=(value)=>{$('message').textContent=value};
const errors={active_zone_required:'Add an active domain to your Cloudflare account, then return to the installer to start a new deployment.',gateway_name_invalid:'Enter a gateway name with at least two letters or numbers.',admin_email_invalid:'Enter a valid administrator email.',additional_admin_emails_invalid:'Check the additional administrator emails.',management_hostname_invalid:'Enter a management hostname under the selected domain.',portal_hostname_invalid:'Enter a different MCP hostname under the selected domain.',gateway_hostnames_invalid:'Choose two different hostnames under the selected domain.',selection_contract_invalid:'Check your gateway details before continuing.'};
async function api(path,body,refused){const response=await fetch(root+path,{method:body===undefined?'GET':'POST',headers:body===undefined?{}:{'content-type':'application/json'},body:body===undefined?undefined:JSON.stringify(body),credentials:'same-origin',cache:'no-store'});const value=await response.json();if(!response.ok){if(response.status===403||response.status===410){$('restart').hidden=false;throw new Error('Your setup session has expired. Return to the installer to review your deployment before starting again.')}if(value.error==='setup_locked')throw new Error('Your final approval has already started. Finish it in Cloudflare.');throw new Error((response.status===400&&refused)||errors[value.reason]||'Setup could not continue. Check your entries and try again.')}return value}
async function action(run){if(busy)return;busy=true;document.querySelectorAll('button').forEach(b=>b.disabled=true);try{await run()}catch(error){message(error.message||'Setup could not continue. Please try again.')}finally{busy=false;document.querySelectorAll('button').forEach(b=>b.disabled=false)}}
function defaults(){const domain=$('domain').value;for(const [id,prefix] of [['management','manage'],['portal','mcp']]){if(!$(id).value||$(id).value===prefix+'.'+previousDomain)$(id).value=prefix+'.'+domain}previousDomain=domain}
function fill(value){setup=value;const empty=value.availableZones.length===0;$('no-domains').hidden=!empty;$('setup').hidden=empty;if(empty){$('heading').textContent='Add a custom domain';$('intro').textContent='Your setup is ready in Cloudflare. A domain is the next step.';message('No active domains were found in the account you approved.');return}$('heading').textContent='Set up your gateway';$('intro').textContent='Choose your gateway’s addresses and who will administer it.';$('domain').replaceChildren(...value.availableZones.map(zone=>{const option=document.createElement('option');option.value=zone.name;option.textContent=zone.name;return option}));if(value.selection){const b=value.selection.basics;$('name').value=b.gatewayName;$('domain').value=b.zoneName;$('management').value=b.managementHostname;$('portal').value=b.portalHostname;$('email').value=b.adminEmail;$('admins').value=b.additionalAdminEmails.join('\n')}defaults();message('Choose your gateway details. You will review them before the final approval.')}
function review(value){setup=value;const plan=value.plan,b=value.selection.basics;$('summary').replaceChildren();for(const [label,text] of [['Gateway',b.gatewayName],['Management address',b.managementHostname],['MCP address',b.portalHostname],['Administrators',plan.managementAdminEmails.join(', ')]]){const dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=label;dd.textContent=text;$('summary').append(dt,dd)}$('resources').replaceChildren(...[...plan.managementResources,...plan.gatewayResources].map(resource=>{const li=document.createElement('li');li.textContent=resource.name;return li}));$('setup').hidden=true;$('review').hidden=false;$('edit').hidden=value.approvalExpired===true;$('approve').textContent=value.approvalExpired===true?'Start a fresh approval':'Approve and finish setup';message(value.approvalExpired===true?'Your Cloudflare approval expired before setup started. Start a fresh approval for these same gateway details.':'Review these details, then approve the final installation in Cloudflare.');credential(value.managementCredential);$('heading').focus()}
const notes={held:'Your gateway has the token. It keeps it in memory and saves it as an encrypted secret when setup finishes.',skipped:'Continuing without a management token. Adding sources and managing team access stay disabled until you add it in Settings.',dropped:'Your gateway no longer holds the token you pasted earlier. Paste it again, or continue without it.'};
function credential(step){$('credential').hidden=true;$('approve').hidden=false;if(!step||!step.createUrl)return;const link=new URL(step.createUrl);if(link.origin!=='https://dash.cloudflare.com')throw new Error('The Cloudflare link could not be verified.');$('credential-link').href=link.href;$('credential-name').textContent=step.name||'';const chosen=step.state==='held'||step.state==='skipped';$('credential').hidden=false;$('credential-entry').hidden=chosen;$('credential-change').hidden=!chosen;$('credential-change').textContent=step.state==='held'?'Use a different token':'Add a token after all';$('approve').hidden=!chosen;const note=Object.hasOwn(notes,String(step.state))?notes[step.state]:'';$('credential-note').textContent=note;$('credential-note').hidden=!note;if(!chosen)message(setup.approvalExpired===true?'Your Cloudflare approval expired before setup started. Add your management token again or continue without it, then start a fresh approval.':'Review these details, then add your management token or continue without it.')}
function chose(result){setup={...setup,managementCredential:{...setup.managementCredential,state:result.managementCredential}};message(setup.approvalExpired===true?'Start a fresh approval for these same gateway details.':'Review these details, then approve the final installation in Cloudflare.');credential(setup.managementCredential)}
$('credential-form').addEventListener('submit',event=>{event.preventDefault();void action(async()=>{const field=$('credential-value'),value=field.value.trim();field.value='';if(!value)throw new Error('Paste the token first, or continue without it.');message('Sending the token to your gateway…');chose(await api('/management-token',{managementToken:value},'That is not a Cloudflare account API token. Account tokens start with cfat_. Copy the token exactly as Cloudflare showed it, or continue without it.'))})});
$('credential-skip').addEventListener('click',()=>{void action(async()=>{$('credential-value').value='';chose(await api('/management-token',{skip:true}))})});
$('credential-change').addEventListener('click',()=>{$('credential-entry').hidden=false;$('credential-change').hidden=true;$('credential-note').hidden=true;$('approve').hidden=true;$('credential-value').focus()});
$('domain').addEventListener('change',defaults);
$('setup').addEventListener('submit',event=>{event.preventDefault();void action(async()=>{message('Preparing your deployment plan…');const selection={schemaVersion:1,basics:{gatewayName:$('name').value,zoneName:$('domain').value,managementHostname:$('management').value,portalHostname:$('portal').value,adminEmail:$('email').value,additionalAdminEmails:$('admins').value.split(/[\n,]+/).map(s=>s.trim()).filter(Boolean)},firstSource:null};review(await api('/configuration',selection))})});
$('edit').addEventListener('click',()=>{$('review').hidden=true;fill(setup)});
$('approve').addEventListener('click',()=>{void action(async()=>{message('Opening Cloudflare for your final approval…');const value=await api('/oauth/start',{});const url=new URL(value.authorizationUrl);if(url.origin!=='https://dash.cloudflare.com')throw new Error('The authorization link could not be verified.');location.assign(url.href)})});
void action(async()=>{const raw=location.hash.slice(1);history.replaceState(null,'',root);if(raw){const normalized=raw.replace(/-/g,'+').replace(/_/g,'/');const handoff=JSON.parse(new TextDecoder().decode(Uint8Array.from(atob(normalized.padEnd(Math.ceil(normalized.length/4)*4,'=')),c=>c.charCodeAt(0))));await api('/continue',handoff);if(!handoff.setupPermit){const value=await api('/oauth/start',{});location.assign(value.authorizationUrl);return}}const value=await api('/setup');fill(value);if(value.plan)review(value)}).then(()=>{if($('setup').hidden&&$('review').hidden&&$('no-domains').hidden)$('restart').hidden=false});
})();
</script></main></body></html>`, { headers: {
    'content-type': 'text/html; charset=utf-8', 'cache-control': 'no-store',
    'content-security-policy': `default-src 'none'; script-src 'nonce-${nonce}'; connect-src 'self'; style-src 'unsafe-inline'; frame-ancestors 'none'; base-uri 'none'; form-action 'none'`,
    'referrer-policy': 'no-referrer', 'x-content-type-options': 'nosniff', 'cross-origin-opener-policy': 'same-origin',
  } });
}
